### ISSUE TITLE
Create first basic domain diagram for contents of chapter 1 of core rulebook

### ISSUE THREAD

**Issue by bumblepie** [bumblepie/dark-heresy-api#1]
### Description
Basically go through the chapter 1 of the core rulebook, identify key concepts of the domain and how they relate to each other. Create domain diagrams that make sense - group relevant concepts together (don't map everything onto one massive diagram - each diagram should describe one key concept or group of concepts). This is an initial understanding, so it doesn't need to be perfect.

### Tasks
- [x] Read chapter 1 of core rulebook
- [x] Identify key domain concepts and their relationships
- [x] Create domain diagrams for key concepts, iterate on these
- [x] Upload diagrams to wiki

**Comment by bumblepie** [comment]
See diagrams at:
- https://github.com/bumblepie/dark-heresy-api/wiki/Domain-Characteristic
- https://github.com/bumblepie/dark-heresy-api/wiki/Domain-Test-and-Roll
