### ISSUE TITLE
Create first basic domain diagram for contents of chapter 3 of core rulebook

### ISSUE THREAD

**Issue by bumblepie** [bumblepie/dark-heresy-api#3]
### Description
Basically go through the chapter 3 of the core rulebook, identify key concepts of the domain and how they relate to each other. Create domain diagrams that make sense - group relevant concepts together (don't map everything onto one massive diagram - each diagram should describe one key concept or group of concepts). This is an initial understanding, so it doesn't need to be perfect.

### Tasks
- [ ] Read chapter 3 of core rulebook
- [ ] Identify key domain concepts and their relationships
- [ ] Create domain diagrams for key concepts, iterate on these
- [ ] Upload diagrams to wiki
